### PR TITLE
Move more Kythe indexing artifacts into flat_hash_set.

### PR DESCRIPTION
**Pull request by hzeller**
Signed-off-by: Henner Zeller <hzeller@google.com>

### CODE REVIEW

**Comment by hzeller** [comment]
WIP. TODO

 * Quantify performance improvement
 * Remove now unnecessary code for various `operator<()`

**Comment by hzeller** [comment]
A particular large 240MiB input file was parsed about 9% faster (425s instead of 467s) and about 10% less memory (52GiB instead of 58GiB).
(also with #1184 applied beforehand)

**Comment by hzeller** [comment]
The savings don't seem super-significant quite yet.

**Comment by hzeller** [comment]
Tested in different environment also using tcmalloc (TODO: add to Verible by default), it is actually 43% faster. So looks worthwhile

**Comment by hzeller** [comment]
#1194 moves the struct into the *.cc file, so if that is submitted first, this will need to have a manual merge.

**Review by ivan444 — APPROVED** [review]

**Pull request merged**
