### PR TITLE
Include links to verible-linter-action in documentation.

### PR DESCRIPTION
**Pull request by hzeller**
Signed-off-by: Henner Zeller <hzeller@google.com>

### CODE REVIEW

**Review by mithro — APPROVED** [review]
LGTM

**Review by tgorochowik — APPROVED** [review]
Should we also mention: https://github.com/chipsalliance/verible-formatter-action ?

**Comment by hzeller** [comment]
@tgorochowik yes - will do that next.

**Comment by hzeller** [comment]
@tgorochowik done.

**Pull request merged**
