### PR TITLE
Add arm64 job

### PR DESCRIPTION
**Pull request by RRozak**
It adds ARM64 testing jobs and compiled binaries to releases.

### CODE REVIEW

**Review by hzeller — COMMENTED** [review]
LGTM, very nice!

Adding Tim and Unai as they have been working on the release stuff before, and probably also want to have a look

**Comment by RRozak** [comment]
Thanks for the information. I excluded these tests.

**Comment by hzeller** [comment]
Haven't heard any complaints from @umarcor or @mithro so will merge later today.

In the meantime: are there possibly some updated machine tags needed like in #1735 @RRozak ?

**Comment by AdamOlech** [comment]
@hzeller it would definitely be recommended to do that. Preferably, all PRs should be updated to include the new set of labels. Otherwise, they might get picked up by wrong runners.

**Comment by RRozak** [comment]
I rebased the branch to the current master

**Comment by hzeller** [comment]
Alright, merged. Thanks everyone!

**Pull request merged**
