### PR TITLE
Update Kythe version used.

### PR DESCRIPTION
**Pull request by hzeller**
Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Comment by hzeller** [comment]
Looks like this pulls in a [dependency to rust](https://github.com/chipsalliance/verible/runs/8043721927?check_suite_focus=true#step:4:182) now. More work needed.

**Comment by hzeller** [comment]
@ivan444 do you see how we can reduce the dependencies that we don't actually need in our context ?

**Comment by ivan444** [comment]
This is something for discussion with Kythe team. I'm going to open an issue with them.

I know how to reduce the dependency, but that would imply a surgery of their release. Pretty fragile.

**Comment by ivan444** [comment]
Opened https://github.com/kythe/kythe/issues/5371

BTW. the workaround is not as complicated as I feared. Just fork `extractors.bazelrc`, drop the languages that we don't care about, and edit `--bazelrc` at `.github/bin/run-kythe.sh`. Tested locally.

**Pull request closed without merging**
