### PR TITLE
Fix AUTO port expansion in module header

### PR DESCRIPTION
**Pull request by kbieganski**
Before this patch, AUTO port expansion in module headers generates incorrect syntax, as port declarations are being separated by `;`, which is only correct in module body. This change fixes that by choosing the correct delimiter based on the context.

### CODE REVIEW

**Comment by hzeller** [comment]
If we do the `repeat` in the `TestTextEditsWithProject()` - shoudn't this catch invalid syntax as it builds a VerilogProject, which internally does a parse of the file ?

**Comment by kbieganski** [comment]
It does, but AUTO ports in module headers weren't tested.

**Comment by kbieganski** [comment]
I pushed an assert to check if the file was actually parsed.

**Review by hzeller — APPROVED** [review]
Maybe having a testing fixture manually parse all inputs and generated outputs with `VerilogAnalyzer::AnalyzeAutomaticMode()` might be a good secondary test in future refinements of the test.

**Comment by hzeller** [comment]
Ha, LOL, so you already added some extra verification while I was writing my last message :)

**Pull request merged**
